// ============================================================
//  CollisionSystem — Runtime collision & trigger detection.
//
//  Works alongside PhysicsWorld.  For each trigger component on a
//  GameObject it creates a Rapier sensor collider.  Uses Rapier's
//  EventQueue to reliably receive collision/intersection events
//  during the physics step, then dispatches overlap begin/end
//  and hit callbacks to blueprint scripts.
//
//  This is modelled after Unreal Engine's collision system:
//    - Trigger components generate OnBeginOverlap / OnEndOverlap
//    - Both the trigger owner AND the other actor receive events
//    - Events are filtered by component name for per-component
//      binding (like UE's "On Component Begin Overlap")
//    - Hit events fire for blocking (physics) collisions
//
//  The system exposes per-GameObject callback hooks that the
//  ScriptComponent runtime code (generated by the node editor)
//  can subscribe to.
// ============================================================

import RAPIER from '@dimforge/rapier3d-compat';
import * as THREE from 'three';
import type { Scene } from './Scene';
import type { GameObject } from './GameObject';
import type { PhysicsWorld } from './PhysicsWorld';
import type { PhysicsConfig } from '../editor/ActorAsset';
import {
  triggerSensorGroups,
  type CollisionConfig,
  type BoxShapeDimensions,
  type SphereShapeDimensions,
  type CapsuleShapeDimensions,
  type OverlapEvent,
  type HitEvent,
} from './CollisionTypes';

// ---- Callback signatures ----

export type OverlapCallback = (event: OverlapEvent) => void;
export type HitCallback = (event: HitEvent) => void;

// ---- Per-GameObject collision state ----

export interface CollisionCallbacks {
  onBeginOverlap: OverlapCallback[];
  onEndOverlap: OverlapCallback[];
  onHit: HitCallback[];
}

/** Sensor handle → game-object + component metadata */
interface SensorEntry {
  gameObjectId: number;
  colliderHandle: number;
  componentName: string;
  componentIndex: number;
  config: CollisionConfig;
}

// ============================================================
//  CollisionSystem
// ============================================================

export class CollisionSystem {
  /** Per-gameObject event callbacks (keyed by go.id) */
  private _callbacks = new Map<number, CollisionCallbacks>();

  /** All sensor colliders created by this system */
  private _sensors: SensorEntry[] = [];

  /** Rapier collider handle → GameObject ID lookup */
  private _handleToGoId = new Map<number, number>();

  /** Quick lookup: collider handle → sensor entry (if it's a sensor) */
  private _handleToSensor = new Map<number, SensorEntry>();

  /** Fixed Rapier bodies created for non-physics GameObjects */
  private _staticBodies: Array<{ goId: number; rb: RAPIER.RigidBody }> = [];

  /** Active overlaps tracking for query nodes and end-overlap detection */
  private _activeOverlaps = new Map<number, Set<number>>();

  /**
   * Rapier EventQueue — receives collision/intersection events during
   * world.step().  Using the EventQueue is far more reliable than
   * polling intersectionPairsWith() — it hooks directly into the
   * narrow-phase and catches ALL events including kinematic↔kinematic
   * sensor pairs that intersectionPairsWith can miss.
   */
  public eventQueue: RAPIER.EventQueue | null = null;

  // ----------------------------------------------------------
  //  Public API
  // ----------------------------------------------------------

  /** Register event callbacks for a game object (called from generated script code at BeginPlay). */
  registerCallbacks(goId: number): CollisionCallbacks {
    let cbs = this._callbacks.get(goId);
    if (!cbs) {
      cbs = { onBeginOverlap: [], onEndOverlap: [], onHit: [] };
      this._callbacks.set(goId, cbs);
    }
    return cbs;
  }

  getCallbacks(goId: number): CollisionCallbacks | undefined {
    return this._callbacks.get(goId);
  }

  /** Remove all collision callbacks for a game object (called when destroying an actor at runtime). */
  unregisterCallbacks(goId: number): void {
    this._callbacks.delete(goId);
    this._activeOverlaps.delete(goId);
    // Also remove this goId from other actors' active overlap sets
    for (const [, overlaps] of this._activeOverlaps) {
      overlaps.delete(goId);
    }
  }

  getSensorCount(): number {
    return this._sensors.length;
  }

  /** Register an external collider handle → gameObject ID mapping.
   *  Used for character-pawn capsule colliders created after createSensors(). */
  registerColliderHandle(colliderHandle: number, goId: number): void {
    this._handleToGoId.set(colliderHandle, goId);
  }

  isOverlapping(goIdA: number, goIdB: number): boolean {
    return this._activeOverlaps.get(goIdA)?.has(goIdB) ?? false;
  }

  getOverlappingCount(goId: number): number {
    return this._activeOverlaps.get(goId)?.size ?? 0;
  }

  getOverlappingIds(goId: number): number[] {
    const set = this._activeOverlaps.get(goId);
    return set ? Array.from(set) : [];
  }

  // ----------------------------------------------------------
  //  Sensor creation  (called once when Play starts)
  // ----------------------------------------------------------

  createSensors(scene: Scene, physics: PhysicsWorld): void {
    if (!physics.world) return;

    // Create the Rapier EventQueue for reliable event detection.
    // autoDrain=true means the queue is cleared before each world.step(),
    // so we only get events from the current step.
    this.eventQueue = new RAPIER.EventQueue(true);

    // 1. Register existing physics-body colliders
    for (const go of scene.gameObjects) {
      if (!go.rigidBody) continue;
      const rb = go.rigidBody as RAPIER.RigidBody;
      for (let i = 0; i < rb.numColliders(); i++) {
        this._handleToGoId.set(rb.collider(i).handle, go.id);
      }
    }

    // 2. Create sensor colliders for trigger components
    for (const go of scene.gameObjects) {
      const triggerComps = (go as any)._triggerComponents as Array<{
        config: CollisionConfig;
        name: string;
        index: number;
        offset: { x: number; y: number; z: number };
      }> | undefined;

      if (!triggerComps || triggerComps.length === 0) continue;

      for (const tc of triggerComps) {
        if (!tc.config.enabled) continue;

        const colDesc = this._colliderDescFromConfig(tc.config);
        if (!colDesc) continue;

        // Mark as sensor so Rapier generates intersection events (not blocking contacts)
        if (tc.config.collisionMode === 'trigger') colDesc.setSensor(true);

        // Enable collision detection with ALL body types (dynamic, kinematic, fixed)
        // This is critical for kinematic character-pawn capsules to trigger events.
        colDesc.setActiveCollisionTypes(RAPIER.ActiveCollisionTypes.ALL);
        colDesc.setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS);
        colDesc.setCollisionGroups(triggerSensorGroups());

        const pos = go.mesh.position;
        const ox = tc.offset?.x ?? 0, oy = tc.offset?.y ?? 0, oz = tc.offset?.z ?? 0;

        const rb = physics.world.createRigidBody(
          RAPIER.RigidBodyDesc.kinematicPositionBased()
            .setTranslation(pos.x + ox, pos.y + oy, pos.z + oz),
        );

        if (!(go as any)._triggerBodies) (go as any)._triggerBodies = [];
        (go as any)._triggerBodies.push({ rb, offset: { x: ox, y: oy, z: oz } });

        const collider = physics.world.createCollider(colDesc, rb);

        const entry: SensorEntry = {
          gameObjectId: go.id,
          colliderHandle: collider.handle,
          componentName: tc.name,
          componentIndex: tc.index,
          config: tc.config,
        };
        this._sensors.push(entry);
        this._handleToGoId.set(collider.handle, go.id);
        this._handleToSensor.set(collider.handle, entry);

        console.log(
          `[Collision] sensor "${tc.name}" on "${go.name}" id=${go.id}` +
          ` shape=${tc.config.shape} handle=${collider.handle}` +
          ` pos=(${(pos.x + ox).toFixed(1)},${(pos.y + oy).toFixed(1)},${(pos.z + oz).toFixed(1)})`,
        );
      }
    }

    // 3. Create fixed colliders for non-physics, non-pawn GameObjects
    //    so sensors can detect overlaps with static meshes.
    for (const go of scene.gameObjects) {
      if (go.rigidBody) continue;
      if (go.actorType === 'characterPawn' || go.actorType === 'spectatorPawn') continue;

      // Skip GameObjects that ARE trigger-only actors (they have no real mesh geometry
      // to create a blocking collider for — they only have sensor colliders).
      const hasTriggerSensors = this._sensors.some(s => s.gameObjectId === go.id);

      const pos = go.mesh.position;
      const rot = go.mesh.quaternion;

      // Check if this GO has any static mesh component children that need colliders
      const hasStaticMeshChildren = go.mesh.children.some(
        (c) => c.userData?.__isStaticMesh,
      );

      const geo = go.mesh.geometry;
      // If no root geometry and no static mesh children, skip
      if (!geo && !hasStaticMeshChildren) continue;

      // Skip invisible placeholder meshes (e.g. DefaultSceneRoot with tiny geometry)
      if (geo) {
        const params = (geo as any).parameters;
        if (params && params.width && params.width < 0.01) {
          if (!hasStaticMeshChildren) continue;
        }
      }

      const rb = physics.world!.createRigidBody(
        RAPIER.RigidBodyDesc.fixed()
          .setTranslation(pos.x, pos.y, pos.z)
          .setRotation({ x: rot.x, y: rot.y, z: rot.z, w: rot.w }),
      );

      // Root geometry collider (if it exists and is large enough)
      if (geo) {
        const params = (geo as any).parameters;
        const skipRoot = params && params.width && params.width < 0.01;
        if (!skipRoot) {
          const colDesc = this._colliderDescFromGeometry(geo);
          colDesc.setActiveCollisionTypes(RAPIER.ActiveCollisionTypes.ALL);
          colDesc.setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS);
          const col = physics.world!.createCollider(colDesc, rb);
          if (!hasTriggerSensors) {
            this._handleToGoId.set(col.handle, go.id);
          }
        }
      }

      this._staticBodies.push({ goId: go.id, rb });

      // Child meshes
      for (const child of go.mesh.children) {
        if (child.userData?.__isTriggerHelper) continue;
        if (child.userData?.__isLightHelper) continue;
        if (child.userData?.__isComponentHelper) continue;
        if (child.userData?.__lightCompName) continue;
        if (child.userData?.__isSkeletalMesh) continue;

        // Handle static mesh component Groups — use collision data or traverse sub-meshes
        if (child.userData?.__isStaticMesh) {
          this._addStaticMeshFixedColliders(
            child as THREE.Group, rb, go.id, hasTriggerSensors, physics,
          );
          continue;
        }

        if (!(child as any).isMesh) continue;
        const mesh = child as THREE.Mesh;
        if (!mesh.geometry) continue;
        const cDesc = this._colliderDescFromGeometry(mesh.geometry);
        cDesc.setTranslation(mesh.position.x, mesh.position.y, mesh.position.z);
        if (mesh.quaternion) {
          cDesc.setRotation({ x: mesh.quaternion.x, y: mesh.quaternion.y, z: mesh.quaternion.z, w: mesh.quaternion.w });
        }
        cDesc.setActiveCollisionTypes(RAPIER.ActiveCollisionTypes.ALL);
        cDesc.setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS);
        const cCol = physics.world!.createCollider(cDesc, rb);
        if (!hasTriggerSensors) {
          this._handleToGoId.set(cCol.handle, go.id);
        }
      }
    }

    console.log(
      `[Collision] ready — sensors=${this._sensors.length}` +
      ` callbacks=${this._callbacks.size} handles=${this._handleToGoId.size}` +
      ` eventQueue=${!!this.eventQueue}`,
    );
  }

  // ----------------------------------------------------------
  //  Runtime resize
  // ----------------------------------------------------------

  resizeSensor(physics: PhysicsWorld, goId: number, componentIndex: number, config: CollisionConfig): void {
    if (!physics.world) return;
    const idx = this._sensors.findIndex(s => s.gameObjectId === goId && s.componentIndex === componentIndex);
    if (idx === -1) return;
    const entry = this._sensors[idx];

    const colDesc = this._colliderDescFromConfig(config);
    if (!colDesc) return;

    const oldCol = physics.world.getCollider(entry.colliderHandle);
    if (!oldCol) return;

    const parentBody = oldCol.parent();
    physics.world.removeCollider(oldCol, false);
    this._handleToGoId.delete(entry.colliderHandle);
    this._handleToSensor.delete(entry.colliderHandle);

    if (config.collisionMode === 'trigger') colDesc.setSensor(true);
    colDesc.setActiveCollisionTypes(RAPIER.ActiveCollisionTypes.ALL);
    colDesc.setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS);
    colDesc.setCollisionGroups(triggerSensorGroups());

    const newCol = physics.world.createCollider(colDesc, parentBody!);
    entry.colliderHandle = newCol.handle;
    entry.config = config;
    this._handleToGoId.set(newCol.handle, goId);
    this._handleToSensor.set(newCol.handle, entry);
  }

  // ----------------------------------------------------------
  //  Per-frame: sync sensor positions
  // ----------------------------------------------------------

  syncSensorPositions(scene: Scene, physics: PhysicsWorld): void {
    if (!physics.world) return;
    for (const go of scene.gameObjects) {
      const bodies = (go as any)._triggerBodies as Array<{
        rb: RAPIER.RigidBody;
        offset: { x: number; y: number; z: number };
      }> | undefined;
      if (!bodies) continue;
      const p = go.mesh.position;
      for (const { rb, offset } of bodies) {
        rb.setNextKinematicTranslation({
          x: p.x + offset.x,
          y: p.y + offset.y,
          z: p.z + offset.z,
        });
      }
    }
  }

  // ----------------------------------------------------------
  //  Per-frame: detect & dispatch events via EventQueue
  // ----------------------------------------------------------

  /** Cached lookup map: go.id → GameObject, rebuilt once per processEvents call */
  private _cachedGoById = new Map<number, GameObject>();

  processEvents(scene: Scene, physics: PhysicsWorld): void {
    if (!physics.world || !this.eventQueue) return;

    const goById = this._cachedGoById;
    goById.clear();
    for (const go of scene.gameObjects) goById.set(go.id, go);

    // ── Drain collision events from Rapier's EventQueue ──
    // The EventQueue receives events directly from the narrow-phase during
    // world.step(), making it far more reliable than polling intersectionPairsWith().
    // Each event contains (handle1, handle2, started) where:
    //   - handle1, handle2: collider handles involved
    //   - started: true = collision/intersection just began, false = just ended
    this.eventQueue.drainCollisionEvents((handle1: number, handle2: number, started: boolean) => {
      const goId1 = this._handleToGoId.get(handle1);
      const goId2 = this._handleToGoId.get(handle2);

      // Skip if either handle isn't mapped to a game object
      if (goId1 === undefined || goId2 === undefined) return;
      // Skip self-collisions
      if (goId1 === goId2) return;

      // Determine if this is a sensor (overlap) event or a contact (hit) event
      const sensor1 = this._handleToSensor.get(handle1);
      const sensor2 = this._handleToSensor.get(handle2);
      const isSensorEvent = !!(sensor1 || sensor2);

      if (isSensorEvent) {
        // ── Overlap event (sensor/trigger) ──
        // Identify which is the sensor and which is the other
        const sensorEntry = sensor1 || sensor2;
        const sensorHandle = sensorEntry!.colliderHandle;
        const sensorGoId = sensorEntry!.gameObjectId;
        const otherGoId = sensorGoId === goId1 ? goId2 : goId1;

        if (started) {
          this._fireOverlapBegin(sensorGoId, otherGoId, sensorHandle, goById);
        } else {
          this._fireOverlapEnd(sensorGoId, otherGoId, sensorHandle, goById);
        }
      } else {
        // ── Contact/hit event (blocking collision) ──
        if (started) {
          this._fireHit(goId1, goId2, handle1, handle2, physics, goById);
        }
      }
    });

    // Also drain contact force events (for future use)
    this.eventQueue.drainContactForceEvents((_event) => {
      // Currently unused — could be used for impact force thresholds
    });
  }

  reset(): void {
    this._callbacks.clear();
    this._sensors = [];
    this._staticBodies = [];
    this._handleToGoId.clear();
    this._handleToSensor.clear();
    this._activeOverlaps.clear();
    if (this.eventQueue) {
      this.eventQueue.free();
      this.eventQueue = null;
    }
  }

  // ==========================================================
  //  Private — fire overlap callbacks (UE-style: both actors)
  // ==========================================================

  private _fireOverlapBegin(
    sensorGoId: number, otherGoId: number,
    sensorHandle: number, goById: Map<number, GameObject>,
  ): void {
    const goA = goById.get(sensorGoId);
    const goB = goById.get(otherGoId);
    if (!goA || !goB) return;

    // Track active overlaps
    if (!this._activeOverlaps.has(sensorGoId)) this._activeOverlaps.set(sensorGoId, new Set());
    if (!this._activeOverlaps.has(otherGoId)) this._activeOverlaps.set(otherGoId, new Set());
    this._activeOverlaps.get(sensorGoId)!.add(otherGoId);
    this._activeOverlaps.get(otherGoId)!.add(sensorGoId);

    const sensorA = this._handleToSensor.get(sensorHandle);
    const sensorB = this._sensors.find(s => s.gameObjectId === otherGoId && s.colliderHandle !== sensorHandle);
    const compA = sensorA?.componentName ?? 'Root';

    console.log(`[Collision] BeginOverlap "${goA.name}" ↔ "${goB.name}" sensor="${compA}"`);

    // Fire on A (sensor owner) — like UE OnComponentBeginOverlap
    const cbsA = this._callbacks.get(sensorGoId);
    if (cbsA && cbsA.onBeginOverlap.length > 0) {
      const evt: OverlapEvent = {
        otherActorName: goB.name,
        otherActorId: goB.id,
        selfComponentName: compA,
        selfComponentIndex: sensorA?.componentIndex ?? -1,
      };
      for (const cb of cbsA.onBeginOverlap) {
        try { cb(evt); } catch (e) { console.error('[Collision] beginOverlap error:', e); }
      }
    }

    // Fire on B (other actor) — like UE OnActorBeginOverlap on the overlapping actor
    const cbsB = this._callbacks.get(otherGoId);
    if (cbsB && cbsB.onBeginOverlap.length > 0) {
      const evt: OverlapEvent = {
        otherActorName: goA.name,
        otherActorId: goA.id,
        selfComponentName: sensorB?.componentName ?? 'Root',
        selfComponentIndex: sensorB?.componentIndex ?? -1,
      };
      for (const cb of cbsB.onBeginOverlap) {
        try { cb(evt); } catch (e) { console.error('[Collision] beginOverlap error:', e); }
      }
    }
  }

  private _fireOverlapEnd(
    sensorGoId: number, otherGoId: number,
    sensorHandle: number, goById: Map<number, GameObject>,
  ): void {
    this._activeOverlaps.get(sensorGoId)?.delete(otherGoId);
    this._activeOverlaps.get(otherGoId)?.delete(sensorGoId);

    const goA = goById.get(sensorGoId);
    const goB = goById.get(otherGoId);
    if (!goA || !goB) return;

    const sensorA = this._handleToSensor.get(sensorHandle);
    const sensorB = this._sensors.find(s => s.gameObjectId === otherGoId && s.colliderHandle !== sensorHandle);

    console.log(`[Collision] EndOverlap "${goA.name}" ↔ "${goB.name}" sensor="${sensorA?.componentName ?? 'Root'}"`);

    const cbsA = this._callbacks.get(sensorGoId);
    if (cbsA) {
      const evt: OverlapEvent = {
        otherActorName: goB.name, otherActorId: goB.id,
        selfComponentName: sensorA?.componentName ?? 'Root',
        selfComponentIndex: sensorA?.componentIndex ?? -1,
      };
      for (const cb of cbsA.onEndOverlap) {
        try { cb(evt); } catch (e) { console.error('[Collision] endOverlap error:', e); }
      }
    }

    const cbsB = this._callbacks.get(otherGoId);
    if (cbsB) {
      const evt: OverlapEvent = {
        otherActorName: goA.name, otherActorId: goA.id,
        selfComponentName: sensorB?.componentName ?? 'Root',
        selfComponentIndex: sensorB?.componentIndex ?? -1,
      };
      for (const cb of cbsB.onEndOverlap) {
        try { cb(evt); } catch (e) { console.error('[Collision] endOverlap error:', e); }
      }
    }
  }

  // ==========================================================
  //  Private — fire hit callbacks (blocking contact events)
  // ==========================================================

  private _fireHit(
    goId1: number, goId2: number,
    handle1: number, handle2: number,
    physics: PhysicsWorld, goById: Map<number, GameObject>,
  ): void {
    if (!physics.world) return;

    const go1 = goById.get(goId1);
    const go2 = goById.get(goId2);
    if (!go1 || !go2) return;

    // Extract contact details from the narrow phase
    let ip = { x: 0, y: 0, z: 0 };
    let inorm = { x: 0, y: 1, z: 0 };
    let imp = 0;

    physics.world.narrowPhase.contactPair(handle1, handle2, (m, _f) => {
      const n = m.normal();
      inorm = { x: n.x, y: n.y, z: n.z };
      if (m.numContacts() > 0) {
        const p = m.localContactPoint1(0);
        if (p) ip = { x: p.x, y: p.y, z: p.z };
        imp = Math.abs(m.contactImpulse(0));
      }
    });

    let hv = { x: 0, y: 0, z: 0 };
    if (go1.rigidBody && go2.rigidBody) {
      const v1 = go1.rigidBody.linvel();
      const v2 = go2.rigidBody.linvel();
      hv = { x: v1.x - v2.x, y: v1.y - v2.y, z: v1.z - v2.z };
    }

    // Fire on go1
    const cbs1 = this._callbacks.get(goId1);
    if (cbs1 && cbs1.onHit.length > 0) {
      const se = this._sensors.find(s => s.gameObjectId === goId1);
      const evt: HitEvent = {
        otherActorName: go2.name, otherActorId: go2.id,
        impactPoint: ip, impactNormal: inorm, hitVelocity: hv, impulse: imp,
        selfComponentName: se?.componentName ?? 'Root',
        selfComponentIndex: se?.componentIndex ?? -1,
      };
      for (const cb of cbs1.onHit) {
        try { cb(evt); } catch (e) { console.error('[Collision] onHit error:', e); }
      }
    }

    // Fire on go2
    const cbs2 = this._callbacks.get(goId2);
    if (cbs2 && cbs2.onHit.length > 0) {
      const se = this._sensors.find(s => s.gameObjectId === goId2);
      const evt: HitEvent = {
        otherActorName: go1.name, otherActorId: go1.id,
        impactPoint: { x: ip.x, y: ip.y, z: ip.z },
        impactNormal: { x: -inorm.x, y: -inorm.y, z: -inorm.z },
        hitVelocity: { x: -hv.x, y: -hv.y, z: -hv.z },
        impulse: imp,
        selfComponentName: se?.componentName ?? 'Root',
        selfComponentIndex: se?.componentIndex ?? -1,
      };
      for (const cb of cbs2.onHit) {
        try { cb(evt); } catch (e) { console.error('[Collision] onHit error:', e); }
      }
    }
  }

  // ==========================================================
  //  Private — helpers
  // ==========================================================

  /** Bounding radius for a CollisionConfig shape. */
  private _boundingRadius(config: CollisionConfig): number {
    const dim = config.dimensions;
    switch (config.shape) {
      case 'sphere': return (dim as SphereShapeDimensions).radius;
      case 'box': {
        const d = dim as BoxShapeDimensions;
        return Math.sqrt((d.width / 2) ** 2 + (d.height / 2) ** 2 + (d.depth / 2) ** 2);
      }
      case 'capsule': {
        const d = dim as CapsuleShapeDimensions;
        return d.height / 2 + d.radius;
      }
    }
    return 1;
  }

  /** Build ColliderDesc from Three.js geometry (for static colliders). */
  private _colliderDescFromGeometry(geo: THREE.BufferGeometry): RAPIER.ColliderDesc {
    if (geo.type === 'BoxGeometry') {
      const p = (geo as any).parameters;
      return RAPIER.ColliderDesc.cuboid(p.width / 2, p.height / 2, p.depth / 2);
    }
    if (geo.type === 'SphereGeometry') {
      const p = (geo as any).parameters;
      return RAPIER.ColliderDesc.ball(p.radius);
    }
    if (geo.type === 'CylinderGeometry') {
      const p = (geo as any).parameters;
      return RAPIER.ColliderDesc.cylinder(p.height / 2, p.radiusTop);
    }

    // For imported mesh BufferGeometry — compute bounding box and use a cuboid
    if (geo.isBufferGeometry && geo.attributes?.position) {
      geo.computeBoundingBox();
      if (geo.boundingBox) {
        const size = new THREE.Vector3();
        geo.boundingBox.getSize(size);
        if (size.x > 0.001 && size.y > 0.001 && size.z > 0.001) {
          return RAPIER.ColliderDesc.cuboid(size.x / 2, size.y / 2, size.z / 2);
        }
      }
    }

    return RAPIER.ColliderDesc.cuboid(0.5, 0.5, 0.5);
  }

  /**
   * Create fixed colliders for a static mesh component Group.
   * Reads per-component collision config (__compCollision) to determine
   * shape, dimensions, enabled state, and mode.
   * Falls back to MeshAsset collision data or bounding-box sub-mesh colliders.
   */
  private _addStaticMeshFixedColliders(
    group: THREE.Group,
    rb: RAPIER.RigidBody,
    goId: number,
    hasTriggerSensors: boolean,
    physics: PhysicsWorld,
  ): void {
    if (!physics.world) return;

    const compCollision: CollisionConfig | null = group.userData.__compCollision || null;
    const compPhysics: PhysicsConfig | null = group.userData.__compPhysics || null;

    // Per-component collision disabled → skip entirely
    if (compCollision && !compCollision.enabled) return;
    if (compCollision && compCollision.collisionMode === 'none') return;

    const friction = compPhysics?.friction ?? 0.5;
    const restitution = compPhysics?.restitution ?? 0.3;
    const isSensor = compCollision
      ? compCollision.collisionMode === 'trigger'
      : false;

    const groupPos = group.position;
    const groupQuat = group.quaternion;

    // If per-component collision config specifies a simple shape, use it directly
    if (compCollision && (compCollision.shape === 'box' || compCollision.shape === 'sphere' || compCollision.shape === 'capsule')) {
      let colDesc: RAPIER.ColliderDesc | null = null;
      const dim = compCollision.dimensions;

      if (compCollision.shape === 'box') {
        const d = dim as BoxShapeDimensions;
        colDesc = RAPIER.ColliderDesc.cuboid(d.width / 2, d.height / 2, d.depth / 2);
      } else if (compCollision.shape === 'sphere') {
        const d = dim as SphereShapeDimensions;
        colDesc = RAPIER.ColliderDesc.ball(d.radius);
      } else if (compCollision.shape === 'capsule') {
        const d = dim as CapsuleShapeDimensions;
        colDesc = RAPIER.ColliderDesc.capsule(d.height / 2, d.radius);
      }

      if (colDesc) {
        // Apply collision offset on top of the component group position
        const colOff = compCollision.offset ?? { x: 0, y: 0, z: 0 };
        const colRot = compCollision.rotationOffset ?? { x: 0, y: 0, z: 0 };
        const toRad = (d: number) => (d * Math.PI) / 180;
        const offsetQuat = new THREE.Quaternion().setFromEuler(
          new THREE.Euler(toRad(colRot.x), toRad(colRot.y), toRad(colRot.z)),
        );
        const finalQuat = groupQuat.clone().multiply(offsetQuat);
        colDesc.setTranslation(
          groupPos.x + colOff.x,
          groupPos.y + colOff.y,
          groupPos.z + colOff.z,
        );
        colDesc.setRotation({ x: finalQuat.x, y: finalQuat.y, z: finalQuat.z, w: finalQuat.w });
        colDesc.setFriction(friction);
        colDesc.setRestitution(restitution);
        if (isSensor) colDesc.setSensor(true);
        colDesc.setActiveCollisionTypes(RAPIER.ActiveCollisionTypes.ALL);
        colDesc.setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS);
        const col = physics.world.createCollider(colDesc, rb);
        if (!hasTriggerSensors) {
          this._handleToGoId.set(col.handle, goId);
        }
      }
      return;
    }

    // Otherwise use pre-generated collision data from the MeshAsset
    const collisionData = group.userData.__collisionData;

    if (collisionData && collisionData.hulls && collisionData.hulls.length > 0) {
      for (const hull of collisionData.hulls) {
        let colDesc: RAPIER.ColliderDesc | null = null;

        if (hull.type === 'box' && hull.halfExtents) {
          colDesc = RAPIER.ColliderDesc.cuboid(
            hull.halfExtents.x, hull.halfExtents.y, hull.halfExtents.z,
          );
        } else if (hull.type === 'sphere' && hull.radius != null) {
          colDesc = RAPIER.ColliderDesc.ball(hull.radius);
        } else if (hull.type === 'capsule' && hull.radius != null && hull.height != null) {
          colDesc = RAPIER.ColliderDesc.capsule(hull.height / 2, hull.radius);
        } else if ((hull.type === 'convexHull' || hull.type === 'autoConvex') && hull.vertices.length >= 9) {
          const verts = new Float32Array(hull.vertices);
          const desc = RAPIER.ColliderDesc.convexHull(verts);
          if (desc) colDesc = desc;
        }

        if (!colDesc && hull.halfExtents) {
          colDesc = RAPIER.ColliderDesc.cuboid(
            hull.halfExtents.x, hull.halfExtents.y, hull.halfExtents.z,
          );
        }

        if (colDesc) {
          const cx = groupPos.x + (hull.center?.x ?? 0);
          const cy = groupPos.y + (hull.center?.y ?? 0);
          const cz = groupPos.z + (hull.center?.z ?? 0);
          colDesc.setTranslation(cx, cy, cz);
          colDesc.setRotation({ x: groupQuat.x, y: groupQuat.y, z: groupQuat.z, w: groupQuat.w });
          colDesc.setFriction(friction);
          colDesc.setRestitution(restitution);
          if (isSensor) colDesc.setSensor(true);
          colDesc.setActiveCollisionTypes(RAPIER.ActiveCollisionTypes.ALL);
          colDesc.setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS);
          const col = physics.world.createCollider(colDesc, rb);
          if (!hasTriggerSensors) {
            this._handleToGoId.set(col.handle, goId);
          }
        }
      }
      return;
    }

    // Fallback: traverse sub-meshes and create bounding-box colliders
    group.traverse((child) => {
      if (!(child as any).isMesh) return;
      const mesh = child as THREE.Mesh;
      if (!mesh.geometry) return;

      const colDesc = this._colliderDescFromGeometry(mesh.geometry);

      const worldPos = new THREE.Vector3();
      mesh.getWorldPosition(worldPos);
      const rootInv = new THREE.Matrix4();
      if (group.parent) {
        rootInv.copy(group.parent.matrixWorld).invert();
        worldPos.applyMatrix4(rootInv);
      }

      const worldQuat = new THREE.Quaternion();
      mesh.getWorldQuaternion(worldQuat);

      colDesc.setTranslation(worldPos.x, worldPos.y, worldPos.z);
      colDesc.setRotation({ x: worldQuat.x, y: worldQuat.y, z: worldQuat.z, w: worldQuat.w });
      colDesc.setFriction(friction);
      colDesc.setRestitution(restitution);
      if (isSensor) colDesc.setSensor(true);
      colDesc.setActiveCollisionTypes(RAPIER.ActiveCollisionTypes.ALL);
      colDesc.setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS);
      const col = physics.world!.createCollider(colDesc, rb);
      if (!hasTriggerSensors) {
        this._handleToGoId.set(col.handle, goId);
      }
    });
  }

  /** Build ColliderDesc from a CollisionConfig. */
  private _colliderDescFromConfig(config: CollisionConfig): RAPIER.ColliderDesc | null {
    const dim = config.dimensions;
    switch (config.shape) {
      case 'box': {
        const d = dim as BoxShapeDimensions;
        return RAPIER.ColliderDesc.cuboid(d.width / 2, d.height / 2, d.depth / 2);
      }
      case 'sphere': {
        const d = dim as SphereShapeDimensions;
        return RAPIER.ColliderDesc.ball(d.radius);
      }
      case 'capsule': {
        const d = dim as CapsuleShapeDimensions;
        return RAPIER.ColliderDesc.capsule(d.height / 2, d.radius);
      }
    }
    return null;
  }
}
