// ============================================================
//  CollisionSystem — Runtime collision & trigger detection.
//
//  Works alongside PhysicsWorld.  For each trigger component on a
//  GameObject it creates a Rapier sensor collider.  Every physics
//  step it reads Rapier's narrow-phase intersection & contact data
//  to detect:
//    • Overlap Begin / End  (for sensors / triggers)
//    • Hit events           (for physics blocking collisions)
//
//  The system exposes per-GameObject callback hooks that the
//  ScriptComponent runtime code (generated by the node editor)
//  can subscribe to.
// ============================================================

import RAPIER from '@dimforge/rapier3d-compat';
import * as THREE from 'three';
import type { Scene } from './Scene';
import type { GameObject } from './GameObject';
import type { PhysicsWorld } from './PhysicsWorld';
import {
  triggerSensorGroups,
  type CollisionConfig,
  type CollisionShapeType,
  type BoxShapeDimensions,
  type SphereShapeDimensions,
  type CapsuleShapeDimensions,
  type OverlapEvent,
  type HitEvent,
} from './CollisionTypes';

// ---- Callback signatures ----

export type OverlapCallback = (event: OverlapEvent) => void;
export type HitCallback = (event: HitEvent) => void;

// ---- Per-GameObject collision state ----

export interface CollisionCallbacks {
  onBeginOverlap: OverlapCallback[];
  onEndOverlap: OverlapCallback[];
  onHit: HitCallback[];
}

/** Sensor handle → game-object + component metadata */
interface SensorEntry {
  gameObjectId: number;
  colliderHandle: number;
  componentName: string;
  componentIndex: number;   // -1 = root trigger
  config: CollisionConfig;
}

// ============================================================
//  CollisionSystem
// ============================================================

export class CollisionSystem {
  /** Per-gameObject event callbacks (keyed by go.id) */
  private _callbacks = new Map<number, CollisionCallbacks>();

  /** All sensor colliders created by this system */
  private _sensors: SensorEntry[] = [];

  /** Rapier collider handle → GameObject ID lookup */
  private _handleToGoId = new Map<number, number>();

  /** Fixed Rapier bodies created for non-physics GameObjects (so sensors can detect them) */
  private _staticBodies: Array<{ goId: number; rb: RAPIER.RigidBody }> = [];

  /** Previous frame's overlapping pairs (stringified "low-high") */
  private _prevOverlaps = new Set<string>();

  /** Active overlaps tracking for query nodes */
  private _activeOverlaps = new Map<number, Set<number>>();

  // ----------------------------------------------------------
  //  Lifecycle
  // ----------------------------------------------------------

  /** Register event callbacks for a game object (called by generated script code at begin-play) */
  registerCallbacks(goId: number): CollisionCallbacks {
    let cbs = this._callbacks.get(goId);
    if (!cbs) {
      cbs = { onBeginOverlap: [], onEndOverlap: [], onHit: [] };
      this._callbacks.set(goId, cbs);
    }
    return cbs;
  }

  getCallbacks(goId: number): CollisionCallbacks | undefined {
    return this._callbacks.get(goId);
  }

  /** Register an external collider handle → gameObject ID mapping.
   *  Used for character-pawn capsule colliders that are created after createSensors(). */
  registerColliderHandle(colliderHandle: number, goId: number): void {
    this._handleToGoId.set(colliderHandle, goId);
  }

  /** Create sensor colliders for all trigger components.  Called when Play starts. */
  createSensors(scene: Scene, physics: PhysicsWorld): void {
    if (!physics.world) return;

    // Register ALL colliders from physics-enabled GameObjects (root + compound child shapes)
    for (const go of scene.gameObjects) {
      if (go.rigidBody) {
        const rb = go.rigidBody as RAPIER.RigidBody;
        for (let i = 0; i < rb.numColliders(); i++) {
          const col = rb.collider(i);
          this._handleToGoId.set(col.handle, go.id);
        }
      }
    }

    for (const go of scene.gameObjects) {
      const triggerComps = (go as any)._triggerComponents as Array<{
        config: CollisionConfig;
        name: string;
        index: number;
        offset: { x: number; y: number; z: number };
      }> | undefined;

      if (!triggerComps || triggerComps.length === 0) continue;

      for (const tc of triggerComps) {
        if (!tc.config.enabled) continue;

        const colDesc = this._colliderDescFromConfig(tc.config);
        if (!colDesc) continue;

        // Position the sensor at the game object's world position + component offset
        const pos = go.mesh.position;
        colDesc.setTranslation(
          pos.x + (tc.offset?.x ?? 0),
          pos.y + (tc.offset?.y ?? 0),
          pos.z + (tc.offset?.z ?? 0),
        );

        // Triggers are sensors (no physical blocking)
        if (tc.config.collisionMode === 'trigger') {
          colDesc.setSensor(true);
        }

        // Enable intersection detection between kinematic bodies (sensor vs pawn)
        // and kinematic vs fixed (sensor vs static meshes).  By default Rapier
        // only computes pairs involving dynamic bodies.
        colDesc.setActiveCollisionTypes(RAPIER.ActiveCollisionTypes.ALL);
        colDesc.setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS);

        // Use Trigger collision groups so channel-based filtering works
        colDesc.setCollisionGroups(triggerSensorGroups());

        // Create a kinematic body to host the sensor collider
        // (sensors need a body in Rapier; kinematic so it follows the mesh)
        const rbDesc = RAPIER.RigidBodyDesc.kinematicPositionBased()
          .setTranslation(pos.x + (tc.offset?.x ?? 0), pos.y + (tc.offset?.y ?? 0), pos.z + (tc.offset?.z ?? 0));
        const rb = physics.world.createRigidBody(rbDesc);
        // Store on go so we can update position every frame
        if (!(go as any)._triggerBodies) (go as any)._triggerBodies = [];
        (go as any)._triggerBodies.push({ rb, offset: tc.offset ?? { x: 0, y: 0, z: 0 } });

        const collider = physics.world.createCollider(colDesc, rb);

        const entry: SensorEntry = {
          gameObjectId: go.id,
          colliderHandle: collider.handle,
          componentName: tc.name,
          componentIndex: tc.index,
          config: tc.config,
        };
        this._sensors.push(entry);
        this._handleToGoId.set(collider.handle, go.id);
      }
    }

    // -----------------------------------------------------------------
    //  Create fixed colliders for non-physics GameObjects so sensors
    //  (triggers) can detect overlaps with them.
    // -----------------------------------------------------------------
    for (const go of scene.gameObjects) {
      if (go.rigidBody) continue; // already has a physics body + colliders

      const geo = go.mesh.geometry;
      if (!geo) continue;

      const pos = go.mesh.position;
      const rot = go.mesh.quaternion;

      const rbDesc = RAPIER.RigidBodyDesc.fixed()
        .setTranslation(pos.x, pos.y, pos.z)
        .setRotation({ x: rot.x, y: rot.y, z: rot.z, w: rot.w });
      const rb = physics.world!.createRigidBody(rbDesc);

      const colDesc = this._colliderDescFromGeometry(geo);
      // Enable collision detection with kinematic bodies (character pawns) and sensors
      colDesc.setActiveCollisionTypes(RAPIER.ActiveCollisionTypes.ALL);
      colDesc.setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS);
      const collider = physics.world!.createCollider(colDesc, rb);
      this._handleToGoId.set(collider.handle, go.id);
      this._staticBodies.push({ goId: go.id, rb });

      // Also create colliders for child component meshes.
      // Skip non-gameplay children: trigger helpers, light helpers,
      // light objects, editor-only helpers, skeletal meshes, groups.
      for (const child of go.mesh.children) {
        if (child.userData?.__isTriggerHelper) continue;
        if (child.userData?.__isLightHelper) continue;
        if (child.userData?.__isComponentHelper) continue;
        if (child.userData?.__lightCompName) continue;   // Three.js light object
        if (child.userData?.__isSkeletalMesh) continue;  // skeletal mesh wrapper
        if (!(child as any).isMesh) continue;
        const mesh = child as THREE.Mesh;
        const childGeo = mesh.geometry;
        if (!childGeo) continue;
        const childColDesc = this._colliderDescFromGeometry(childGeo);
        childColDesc.setTranslation(mesh.position.x, mesh.position.y, mesh.position.z);
        if (mesh.quaternion) {
          childColDesc.setRotation({
            x: mesh.quaternion.x, y: mesh.quaternion.y,
            z: mesh.quaternion.z, w: mesh.quaternion.w,
          });
        }
        childColDesc.setActiveCollisionTypes(RAPIER.ActiveCollisionTypes.ALL);
        childColDesc.setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS);
        const childCol = physics.world!.createCollider(childColDesc, rb);
        this._handleToGoId.set(childCol.handle, go.id);
      }
    }
  }

  /** Update sensor body positions to follow their owning game objects.  Called every physics step. */
  syncSensorPositions(scene: Scene, physics: PhysicsWorld): void {
    if (!physics.world) return;
    for (const go of scene.gameObjects) {
      const bodies = (go as any)._triggerBodies as Array<{
        rb: RAPIER.RigidBody;
        offset: { x: number; y: number; z: number };
      }> | undefined;
      if (!bodies) continue;
      const p = go.mesh.position;
      for (const { rb, offset } of bodies) {
        rb.setNextKinematicTranslation({
          x: p.x + offset.x,
          y: p.y + offset.y,
          z: p.z + offset.z,
        });
      }
    }
  }

  /** Detect overlaps and hits.  Called after physics.step(). */
  processEvents(scene: Scene, physics: PhysicsWorld): void {
    if (!physics.world) return;

    const goById = new Map<number, GameObject>();
    for (const go of scene.gameObjects) goById.set(go.id, go);

    // ---- Overlap detection via sensor intersection tests ----
    const currentOverlaps = new Set<string>();

    this._detectOverlaps(physics, goById, currentOverlaps);
    this._detectHits(physics, goById);

    // ---- Compute begin / end overlaps by diffing with previous frame ----
    // Begin overlaps: in current but not in previous
    for (const key of currentOverlaps) {
      if (!this._prevOverlaps.has(key)) {
        const [idA, idB] = key.split('-').map(Number);
        this._fireOverlapBegin(idA, idB, goById);
      }
    }
    // End overlaps: in previous but not in current
    for (const key of this._prevOverlaps) {
      if (!currentOverlaps.has(key)) {
        const [idA, idB] = key.split('-').map(Number);
        this._fireOverlapEnd(idA, idB, goById);
      }
    }

    this._prevOverlaps = currentOverlaps;
  }

  /** Query: is gameObject A currently overlapping gameObject B? */
  isOverlapping(goIdA: number, goIdB: number): boolean {
    const set = this._activeOverlaps.get(goIdA);
    return set ? set.has(goIdB) : false;
  }

  /** Query: how many actors is this game object currently overlapping? */
  getOverlappingCount(goId: number): number {
    const set = this._activeOverlaps.get(goId);
    return set ? set.size : 0;
  }

  /** Query: get all actor IDs currently overlapping this game object */
  getOverlappingIds(goId: number): number[] {
    const set = this._activeOverlaps.get(goId);
    return set ? Array.from(set) : [];
  }

  /** Cleanup when play stops */
  reset(): void {
    this._callbacks.clear();
    this._sensors = [];
    this._staticBodies = [];
    this._handleToGoId.clear();
    this._prevOverlaps.clear();
    this._activeOverlaps.clear();
  }

  // ----------------------------------------------------------
  //  Internal helpers
  // ----------------------------------------------------------

  private _detectOverlaps(
    physics: PhysicsWorld,
    goById: Map<number, GameObject>,
    currentOverlaps: Set<string>,
  ): void {
    if (!physics.world) return;

    // For each sensor, use intersectionPairsWith to find all colliders intersecting it
    for (const sensor of this._sensors) {
      if (!sensor.config.generateOverlapEvents) continue;

      const sensorCollider = physics.world.getCollider(sensor.colliderHandle);
      if (!sensorCollider) continue;

      // intersectionPairsWith: iterates all colliders in intersection with this sensor
      physics.world.intersectionPairsWith(sensorCollider, (otherCollider: RAPIER.Collider) => {
        const otherHandle = otherCollider.handle;
        if (otherHandle === sensor.colliderHandle) return; // skip self
        const otherGoId = this._handleToGoId.get(otherHandle);
        if (otherGoId === undefined || otherGoId === sensor.gameObjectId) return; // skip same gameObject

        const low = Math.min(sensor.gameObjectId, otherGoId);
        const high = Math.max(sensor.gameObjectId, otherGoId);
        currentOverlaps.add(`${low}-${high}`);
      });
    }
  }

  private _detectHits(
    physics: PhysicsWorld,
    goById: Map<number, GameObject>,
  ): void {
    if (!physics.world) return;

    // For each physics body that has hit callbacks, check contact pairs
    for (const go of goById.values()) {
      if (!go.collider) continue;

      const cbs = this._callbacks.get(go.id);
      if (!cbs || cbs.onHit.length === 0) continue;

      // contactPairsWith iterates all colliders in contact with this collider
      physics.world.contactPairsWith(go.collider, (otherCollider: RAPIER.Collider) => {
        const otherGoId = this._handleToGoId.get(otherCollider.handle);
        if (otherGoId === undefined || otherGoId === go.id) return;

        const otherGo = goById.get(otherGoId);
        if (!otherGo) return;

        // Extract contact data from the narrow phase
        let impactPoint = { x: 0, y: 0, z: 0 };
        let impactNormal = { x: 0, y: 1, z: 0 };
        let impulse = 0;

        // Use narrowPhase.contactPair for manifold details
        physics.world!.narrowPhase.contactPair(
          go.collider!.handle,
          otherCollider.handle,
          (manifold, _flipped) => {
            const normal = manifold.normal();
            impactNormal = { x: normal.x, y: normal.y, z: normal.z };
            if (manifold.numContacts() > 0) {
              const pt = manifold.localContactPoint1(0);
              if (pt) impactPoint = { x: pt.x, y: pt.y, z: pt.z };
              impulse = Math.abs(manifold.contactImpulse(0));
            }
          },
        );

        // Compute hit velocity from rigid bodies
        let hitVelocity = { x: 0, y: 0, z: 0 };
        if (go.rigidBody && otherGo.rigidBody) {
          const v1 = go.rigidBody.linvel();
          const v2 = otherGo.rigidBody.linvel();
          hitVelocity = { x: v1.x - v2.x, y: v1.y - v2.y, z: v1.z - v2.z };
        }

        // Find which sensor this relates to
        const sensorEntry = this._sensors.find(s => s.gameObjectId === go.id);

        const hitEvt: HitEvent = {
          otherActorName: otherGo.name,
          otherActorId: otherGo.id,
          impactPoint,
          impactNormal,
          hitVelocity,
          impulse,
          selfComponentName: sensorEntry?.componentName ?? 'Root',
          selfComponentIndex: sensorEntry?.componentIndex ?? -1,
        };

        for (const cb of cbs.onHit) {
          try { cb(hitEvt); } catch (e) { console.error('[CollisionSystem] onHit error:', e); }
        }
      });
    }
  }

  private _fireOverlapBegin(idA: number, idB: number, goById: Map<number, GameObject>): void {
    const goA = goById.get(idA);
    const goB = goById.get(idB);
    if (!goA || !goB) return;

    // Track active overlaps
    if (!this._activeOverlaps.has(idA)) this._activeOverlaps.set(idA, new Set());
    if (!this._activeOverlaps.has(idB)) this._activeOverlaps.set(idB, new Set());
    this._activeOverlaps.get(idA)!.add(idB);
    this._activeOverlaps.get(idB)!.add(idA);

    // Find sensor entries for context
    const sensorA = this._sensors.find(s => s.gameObjectId === idA);
    const sensorB = this._sensors.find(s => s.gameObjectId === idB);

    // Fire on A
    const cbsA = this._callbacks.get(idA);
    if (cbsA) {
      const evt: OverlapEvent = {
        otherActorName: goB.name,
        otherActorId: goB.id,
        selfComponentName: sensorA?.componentName ?? 'Root',
        selfComponentIndex: sensorA?.componentIndex ?? -1,
      };
      for (const cb of cbsA.onBeginOverlap) {
        try { cb(evt); } catch (e) { console.error('[CollisionSystem] onBeginOverlap error:', e); }
      }
    }

    // Fire on B
    const cbsB = this._callbacks.get(idB);
    if (cbsB) {
      const evt: OverlapEvent = {
        otherActorName: goA.name,
        otherActorId: goA.id,
        selfComponentName: sensorB?.componentName ?? 'Root',
        selfComponentIndex: sensorB?.componentIndex ?? -1,
      };
      for (const cb of cbsB.onBeginOverlap) {
        try { cb(evt); } catch (e) { console.error('[CollisionSystem] onBeginOverlap error:', e); }
      }
    }
  }

  private _fireOverlapEnd(idA: number, idB: number, goById: Map<number, GameObject>): void {
    const goA = goById.get(idA);
    const goB = goById.get(idB);

    // Remove from active overlaps
    this._activeOverlaps.get(idA)?.delete(idB);
    this._activeOverlaps.get(idB)?.delete(idA);

    if (!goA || !goB) return;

    const sensorA = this._sensors.find(s => s.gameObjectId === idA);
    const sensorB = this._sensors.find(s => s.gameObjectId === idB);

    const cbsA = this._callbacks.get(idA);
    if (cbsA) {
      const evt: OverlapEvent = {
        otherActorName: goB.name,
        otherActorId: goB.id,
        selfComponentName: sensorA?.componentName ?? 'Root',
        selfComponentIndex: sensorA?.componentIndex ?? -1,
      };
      for (const cb of cbsA.onEndOverlap) {
        try { cb(evt); } catch (e) { console.error('[CollisionSystem] onEndOverlap error:', e); }
      }
    }

    const cbsB = this._callbacks.get(idB);
    if (cbsB) {
      const evt: OverlapEvent = {
        otherActorName: goA.name,
        otherActorId: goA.id,
        selfComponentName: sensorB?.componentName ?? 'Root',
        selfComponentIndex: sensorB?.componentIndex ?? -1,
      };
      for (const cb of cbsB.onEndOverlap) {
        try { cb(evt); } catch (e) { console.error('[CollisionSystem] onEndOverlap error:', e); }
      }
    }
  }

  /** Build a RAPIER.ColliderDesc from a Three.js BufferGeometry (for static colliders). */
  private _colliderDescFromGeometry(geo: THREE.BufferGeometry): RAPIER.ColliderDesc {
    if (geo.type === 'BoxGeometry') {
      const p = (geo as any).parameters;
      return RAPIER.ColliderDesc.cuboid(p.width / 2, p.height / 2, p.depth / 2);
    } else if (geo.type === 'SphereGeometry') {
      const p = (geo as any).parameters;
      return RAPIER.ColliderDesc.ball(p.radius);
    } else if (geo.type === 'CylinderGeometry') {
      const p = (geo as any).parameters;
      return RAPIER.ColliderDesc.cylinder(p.height / 2, p.radiusTop);
    }
    // Fallback: unit cube
    return RAPIER.ColliderDesc.cuboid(0.5, 0.5, 0.5);
  }

  /** Create a Rapier ColliderDesc from a CollisionConfig */
  private _colliderDescFromConfig(config: CollisionConfig): RAPIER.ColliderDesc | null {
    const dim = config.dimensions;
    switch (config.shape) {
      case 'box': {
        const d = dim as BoxShapeDimensions;
        return RAPIER.ColliderDesc.cuboid(d.width / 2, d.height / 2, d.depth / 2);
      }
      case 'sphere': {
        const d = dim as SphereShapeDimensions;
        return RAPIER.ColliderDesc.ball(d.radius);
      }
      case 'capsule': {
        const d = dim as CapsuleShapeDimensions;
        return RAPIER.ColliderDesc.capsule(d.height / 2, d.radius);
      }
    }
    return null;
  }
}
