// ============================================================
//  GameInstance — Runtime persistent object that survives scene loads.
//  Like UE4's UGameInstance, this object persists across scene
//  transitions and provides shared state (variables) and logic
//  (event graph) accessible from any blueprint via
//  "Get Game Instance" nodes.
// ============================================================

import { ScriptComponent, type ScriptContext } from './ScriptComponent';
/** Minimal inlined type — avoids hard dependency on editor module. */
export interface GameInstanceBlueprintAsset {
  id: string;
  name: string;
  compiledCode: string;
  blueprintData?: any;
  eventGraph?: any;
}

export class GameInstance {
  /** The blueprint asset this instance was created from */
  public asset: GameInstanceBlueprintAsset;
  /** Runtime script component (compiled event graph) */
  public script: ScriptComponent;
  /** Runtime variable storage — blueprint nodes read/write these */
  public variables: Record<string, any> = {};
  /** Registered functions from compiled blueprint code */
  private _functions: Record<string, (...args: any[]) => any> = {};
  /** Registered custom events from compiled blueprint code */
  private _events: Record<string, (...args: any[]) => void> = {};

  private _initialized = false;

  constructor(asset: GameInstanceBlueprintAsset) {
    this.asset = asset;
    this.script = new ScriptComponent();

    // Initialize runtime variables from blueprint defaults
    for (const v of asset.blueprintData.variables) {
      this.variables[v.name] = v.defaultValue;
    }

    // Compile the event graph
    if (asset.compiledCode) {
      this.script.code = asset.compiledCode;
      if (this.script.compile()) {
        console.log(`[GameInstance] Compiled event graph for "${asset.name}"`);
      } else {
        console.warn(`[GameInstance] Failed to compile event graph for "${asset.name}"`);
      }
    }
  }

  /** Fire BeginPlay (only once, even across scene reloads) */
  beginPlay(ctx: ScriptContext): void {
    if (this._initialized) return;
    this._initialized = true;
    this.script.beginPlay(ctx);
    console.log(`[GameInstance] BeginPlay for "${this.asset.name}"`);
  }

  /** Fire Tick each frame */
  tick(ctx: ScriptContext): void {
    if (!this._initialized) return;
    this.script.tick(ctx);
  }

  /** Fire OnDestroy (called only when play stops completely, not on scene transitions) */
  onDestroy(ctx: ScriptContext): void {
    if (!this._initialized) return;
    this.script.onDestroy(ctx);
    this.script.reset();
    this._initialized = false;
    console.log(`[GameInstance] OnDestroy for "${this.asset.name}"`);
  }

  /** Get a variable value by name */
  getVariable(name: string): any {
    return this.variables[name];
  }

  /** Set a variable value by name */
  setVariable(name: string, value: any): void {
    this.variables[name] = value;
  }

  /**
   * Call a compiled function on this Game Instance by name.
   * Functions are generated by the code compiler as `__fn_<Name>` in the preamble
   * and registered via `__gameInstance.__registerFunction(name, fn)` at beginPlay.
   */
  callFunction(name: string, ...args: any[]): any {
    const fn = this._functions[name];
    if (!fn || typeof fn !== 'function') {
      console.warn(`[GameInstance] callFunction: "${name}" not found in "${this.asset.name}"`);
      return undefined;
    }
    return fn(...args);
  }

  /**
   * Trigger a custom event on this Game Instance.
   * Events are generated as `__custom_evt_<Name>` in the preamble
   * and registered via `__gameInstance.__registerEvent(name, fn)` at beginPlay.
   */
  callEvent(name: string, ...args: any[]): void {
    const sanitized = name.replace(/[^a-zA-Z0-9_]/g, '_');
    const fn = this._events[sanitized];
    if (!fn || typeof fn !== 'function') {
      console.warn(`[GameInstance] callEvent: "${name}" not found in "${this.asset.name}"`);
      return;
    }
    fn(...args);
  }

  /** Called from compiled code to register a function at runtime */
  __registerFunction(name: string, fn: (...args: any[]) => any): void {
    this._functions[name] = fn;
  }

  /** Called from compiled code to register a custom event at runtime */
  __registerEvent(name: string, fn: (...args: any[]) => void): void {
    this._events[name] = fn;
  }
}
